
################### English Navigation ########################
[[main]]
name = "services"
URL = "feature"
weight = 1

[[main]]
name = "about"
URL = "about"
weight = 2

# [[main]]
# name = "services"
# URL = "services"
# weight = 3

# [[main]]
# name = "blog"
# URL = "blog"
# weight = 4

[[main]]
name = "contact"
URL = "contact"
weight = 5
